# Generated by Django 4.2 on 2023-06-06 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('company_name', models.CharField(max_length=100, null=True)),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name='address contd')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
                ('state', models.CharField(verbose_name='state')),
                ('pincode', models.CharField(max_length=6, verbose_name='zip code')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('mobile', phone_field.models.PhoneField(max_length=31)),
                ('website', models.URLField(blank=True, null=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employer Profile',
            },
        ),
        migrations.RemoveField(
            model_name='job',
            name='company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_address',
        ),
        migrations.RemoveField(
            model_name='job',
            name='country',
        ),
        migrations.RemoveField(
            model_name='job',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='job',
            name='recruiter',
        ),
        migrations.RemoveField(
            model_name='job',
            name='state',
        ),
        migrations.RemoveField(
            model_name='job',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='applicants',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('internship', 'Internship'), ('remote', 'Remote')], default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Selected',
        ),
    ]
