# Generated by Django 4.2 on 2023-06-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_employerprofile_remove_job_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.URLField(default=''),
        ),
    ]
