# Generated by Django 3.2.16 on 2023-06-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_applicants_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='state',
            field=models.CharField(max_length=100, verbose_name='state'),
        ),
    ]
