# Generated by Django 3.2.16 on 2023-07-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_payment_transaction_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='signature_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Signature ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(blank=True, choices=[('success', 'Success'), ('failure', 'Failure'), ('pending', 'Pending')], default='Pending', max_length=254, null=True, verbose_name='Payment Status'),
        ),
    ]
