# Generated by Django 3.2.16 on 2023-07-06 06:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_auto_20230704_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='access',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=None),
        ),
    ]
