# Generated by Django 4.2 on 2023-06-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_customuser_user_type_customuser_is_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_employee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_employer',
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(default='', error_messages={'required': 'Role must be provided'}, max_length=12),
        ),
    ]
