# Generated by Django 4.2 on 2023-06-09 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0003_rename_skill_employee_skills_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeprofile',
            options={'verbose_name': 'employeeprofile'},
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
