# Generated by Django 3.2.16 on 2023-06-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_education_user_alter_experience_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='state',
            field=models.CharField(max_length=100, verbose_name='state'),
        ),
    ]
